import json
import os
from typing import List, Dict
import chromadb
from chromadb.utils import embedding_functions
from langchain_text_splitters import RecursiveCharacterTextSplitter

class MedicalOpenSourceIngestionPipeline:
    def __init__(self, db_path: str = "./local_chroma_db", collection_name: str = "cancer_treatment_rag"):
        """
        Initializes an open-source, local vector database infrastructure.
        No cloud subscriptions or API keys are required.
        """
        # 1. Initialize persistent local disk storage
        self.chroma_client = chromadb.PersistentClient(path=db_path)
        
        # 2. Configure a free, open-source local embedding model (384 dimensions)
        self.embedding_function = embedding_functions.SentenceTransformerEmbeddingFunction(
            model_name="all-MiniLM-L6-v2"
        )
        
        # 3. Create or get the collection inside Chroma
        self.collection = self.chroma_client.get_or_create_collection(
            name=collection_name,
            embedding_function=self.embedding_function,
            metadata={"hnsw:space": "cosine"} # Use cosine similarity for matching
        )
        
        # 4. Set up medical structural text chunking bounds
        self.text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=800,
            chunk_overlap=150,
            length_function=len,
            separators=["\n\n", "\n", ".", " ", ""]
        )

    def load_transcripts(self, file_path: str) -> List[Dict]:
        """Loads data generated by your YouTube extraction agent."""
        with open(file_path, "r", encoding="utf-8") as f:
            return json.load(f)

    def build_and_insert_vectors(self, raw_videos: List[Dict]):
        """
        Chunks text, automatically calculates embeddings locally, and saves them to disk.
        """
        print(f"🧬 Processing {len(raw_videos)} videos into local open-source vector space...")
        
        for video in raw_videos:
            transcript = video.get("transcript", "")
            if not transcript:
                continue

            # 1. Structural Chunking
            chunks = self.text_splitter.split_text(transcript)
            print(f"🎬 Video '{video['title'][:40]}...' split into {len(chunks)} fragments.")

            # Batch storage containers for Chroma's native bulk insert method
            documents = []
            metadatas = []
            ids = []

            for index, chunk_text in enumerate(chunks):
                # Context enrichment layer: Helps the embedding catch relevant keywords
                enriched_text = f"Source Video: {video['title']} | Content: {chunk_text}"
                
                # Unique string identifier per vector chunk
                vector_id = f"{video['video_id']}_chunk_{index}"
                
                # Structural metadata mapping
                metadata = {
                    "video_id": video["video_id"],
                    "title": video["title"],
                    "link": video["link"],
                    "chunk_index": index,
                    "medical_domain": "oncology"
                }
                
                documents.append(enriched_text)
                metadatas.append(metadata)
                ids.append(vector_id)

            # 2. Local Direct Upload
            # Chroma automatically runs the documents through the embedding function under the hood
            if ids:
                print(f"📤 Storing {len(ids)} chunks to local SQLite file matrix...")
                self.collection.add(
                    documents=documents,
                    metadatas=metadatas,
                    ids=ids
                )
                print(f"✨ Successfully indexed video: {video['video_id']}\n")

# ==========================================
# Execution Block
# ==========================================
if __name__ == "__main__":
    # Initialize Open-Source Pipeline Instance
    pipeline = MedicalOpenSourceIngestionPipeline(
        db_path="./local_chroma_db", 
        collection_name="cancer_treatment_rag"
    )
    
    # Process and Upload local transcripts file
    try:
        raw_data = pipeline.load_transcripts("cancer_treatment_transcripts.json")
        pipeline.build_and_insert_vectors(raw_data)
        print("🎉 Open-Source Pipeline Complete! Database saved locally inside './local_chroma_db'.")
    except FileNotFoundError:
        print("❌ Error: 'cancer_treatment_transcripts.json' file not found. Run your extraction agent first!")
